# Generated by Django 5.1.5 on 2025-01-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('avatar', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('about', models.CharField(max_length=120, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_count', models.IntegerField(default=0)),
                ('readers_count', models.IntegerField(default=0)),
                ('follows_count', models.IntegerField(default=0)),
                ('follow_for', models.JSONField(blank=True, default=list, null=True)),
                ('liked_posts', models.JSONField(blank=True, default=list, null=True)),
                ('official', models.BooleanField(default=False, null=True)),
                ('jwt', models.TextField(blank=True, default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
