# Generated by Django 4.2.26 on 2025-12-06 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('avatar', models.ImageField(default='images/default.png', upload_to='images/')),
                ('about', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_count', models.IntegerField(default=0)),
                ('readers_count', models.IntegerField(default=0)),
                ('follows_count', models.IntegerField(default=0)),
                ('follow_for', models.JSONField(blank=True, default=list, null=True)),
                ('readers', models.JSONField(blank=True, default=list, null=True)),
                ('liked_posts', models.JSONField(blank=True, default=list, null=True)),
                ('liked_comments', models.JSONField(blank=True, default=list, null=True)),
                ('liked_comment_replies', models.JSONField(blank=True, default=list, null=True)),
                ('secret_2fa', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('is2FA', models.BooleanField(default=False)),
                ('official', models.BooleanField(default=False, null=True)),
                ('count_generations_ai', models.IntegerField(blank=True, default=1, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_baned', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('comment_reply', 'Comment Reply'), ('comment_like', 'Comment Like'), ('follow', 'Follow'), ('revived_transaction', 'Recived Transaction'), ('deleted_post', 'Post Deleted'), ('moderation_success', 'Moderation Success'), ('moderation_fail', 'Moderation Fail')], max_length=20)),
                ('text_preview', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.comment')),
                ('comment_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.commentreply')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.post')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorySearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searched_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
