# Generated by Django 5.1.5 on 2025-04-10 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('avatar', models.ImageField(default='images/default.png', upload_to='images/')),
                ('about', models.CharField(default='', max_length=120, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_count', models.IntegerField(default=0)),
                ('readers_count', models.IntegerField(default=0)),
                ('follows_count', models.IntegerField(default=0)),
                ('follow_for', models.JSONField(blank=True, default=list, null=True)),
                ('liked_posts', models.JSONField(blank=True, default=list, null=True)),
                ('secret_2fa', models.CharField(default=None, max_length=100, null=True)),
                ('is2FA', models.BooleanField(default=False)),
                ('official', models.BooleanField(default=False, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorySearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searched_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
