# Generated by Django 5.1.5 on 2025-01-15 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jwt',
        ),
    ]
