name: Production Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl stop nextvibe-celery-worker

            # --- 2. SYNCHRONIZATION ---
            cd /root/NextVibe
            echo "📥 Fetching latest code..."
            git fetch origin main
            git reset --hard origin/main

            # --- 3. PYTHON BACKEND (Django + Celery) ---
            echo "🐍 Updating Python dependencies..."
            ./backend/.venv/bin/pip install -r backend/modules.txt

            echo "🗄️ Running Migrations..."
            ./backend/.venv/bin/python backend/NextVibeAPI/manage.py migrate

            echo "🎨 Collecting Static Files..."
            ./backend/.venv/bin/python backend/NextVibeAPI/manage.py collectstatic --noinput

            # --- 4. GO MODERATION SERVICE ---
            echo "mw Rebuilding Go Binary..."
            cd moderation_service
            /usr/local/go/bin/go build -o moderator_bin .
            cd ..

            # --- 5. RESTART SERVICES ---
            echo "🔄 Restarting Systemd Services..."
            
            # Django Backend
            sudo systemctl restart nextvibe-backend.service
            
            sudo systemctl restart nextvibe-realtime.service
            
            # Celery
            sudo systemctl restart nextvibe-celery-beat.service 
            sudo systemctl restart nextvibe-celery-worker.service 
            
            # Go Moderation
            sudo systemctl restart nextvibe-moderation.service

            sudo systemctl reload nginx

            echo "✅ DEPLOYMENT SUCCESSFUL 🚀"